language: scala

sudo: false

scala:
- 2.11.12
- 2.12.15
- 2.13.4

jdk:
  - openjdk8
  - openjdk11

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt publish
