name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.11.12, 2.12.15, 2.13.8]
        java-version: [8, 11, 17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean test
